export const Icons = {
    arrow : require('../assets/icons/arrow.png'),
    arrowBold : require('../assets/icons/arrowBold.png'),
    arrowLeft : require('../assets/icons/arrowLeft.png'),
    arrowDown : require('../assets/icons/arrowDown.png'),
    filter : require('../assets/icons/filter.png'),
    funnel : require('../assets/icons/funnel.png'),
    settings : require('../assets/icons/settings.png'),
    menu : require('../assets/icons/menuoutline.png'),
    home: require('../assets/icons/home.png'),
    searchBold: require('../assets/icons/searchLine.png'),
    settings: require('../assets/icons/settings.png'),
    star: require('../assets/icons/star.png'),
    ac: require('../assets/icons/ac.png'),
    bed: require('../assets/icons/bed.png'),
    camera: require('../assets/icons/camera.png'),
    tv: require('../assets/icons/tv.png'),
    wifi: require('../assets/icons/wifi.png'),
    canteen: require('../assets/icons/canteen.png'),
};
