export const Images = {

    onBoardImg1 : require('../assets/images/onBoardImg11.jpg'),
    onBoardImg2 : require('../assets/images/onBoardImg5.jpg'),
    onBoardImg3 : require('../assets/images/onBoardImg18.jpg'),

    img1 : require('../assets/images/onBoardImg1.jpg'),
    img2 : require('../assets/images/onBoardImg2.jpg'),
    img3 : require('../assets/images/onBoardImg3.jpg'),
    img4 : require('../assets/images/onBoardImg4.jpg'),
    img5 : require('../assets/images/onBoardImg5.jpg'),
    img6 : require('../assets/images/onBoardImg6.jpg'),
    img7 : require('../assets/images/onBoardImg7.jpg'),
    img8 : require('../assets/images/onBoardImg8.jpg'),
    img9 : require('../assets/images/onBoardImg9.jpg'),
    img10 : require('../assets/images/onBoardImg10.jpg'),
    img11 : require('../assets/images/onBoardImg11.jpg'),
    img12 : require('../assets/images/onBoardImg12.jpg'),
    img13 : require('../assets/images/onBoardImg13.jpg'),
    img14 : require('../assets/images/onBoardImg14.jpg'),
    img15 : require('../assets/images/onBoardImg15.jpg'),
    img16 : require('../assets/images/onBoardImg16.jpg'),
    img17 : require('../assets/images/onBoardImg17.jpg'),
    img18 : require('../assets/images/onBoardImg18.jpg'),

    logo : require('../assets/images/logo.png'),
    FindStay : require('../assets/images/FindStay.png'),
    NoiseBg : require('../assets/images/noiseBG1.png'),
    GlassBG : require('../assets/images/GlassBGedited.png'),
};
